# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: baaf40ea92a209bb0eeec4863cb6260b81839c64b265ebd3a25f0ae27ad240114208ef7c6ae326af60723270036a37ea7967944b016b7a222898210f0f9e013a

test:
  secret_key_base: 7b22f3a5315ff7995f25e2f53be0662feec7617204d00de528fb1b6de4d355cf9bde3fd4fd8ec2ad788698e6bffe019d4e56b41c8083bcafa11cc5f95c3f998b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
